name: "Checks om merge request"

on:
  pull_request:
    branches:
      - main 
jobs:
  release:
    name: checks before merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: install node & yarn 
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
      - name: install yarn 
        run: npm install --global yarn
      - name: install third party libs
        run: yarn install
      - name: test library
        run: yarn test
      - name: build library
        run: yarn build